### PR TITLE
Correct subfilters' class names

### PR DESCRIPTION
**Pull request by jasl**
In my Mac (FS is HFS+), the filename `BrightnessSubFilter.java` but class name is `BrightnessSubfilter` that made compiling failure, according to the base class called SubFiler, I correct all sub-filters naming convention.

I also found current master branch can't pass compiling because quality check tipping there have an unused import issue, I fix that too.

In addition, I update gradle version to 2.1.2, and fix a warning that Android Studio suggests.

I also refactor `ThumbnailsAdapter`, removing NineOldAndroid (there is no need when SDK version above 14).

### CODE REVIEW

**Comment by varunest** [comment]
Modified files don't match with their respective class names.

**Comment by jasl** [comment]
Do you check the branch to your machine? Github's Files changed tab seems shows wrong filename.

I rename files by `git mv`, and this PR is actually intend to fix filename in git logs.

**Comment by varunest** [comment]
Yeah, this happens sometimes. Its a bug. I think deleting and then adding the same files would solve this.

**Comment by jasl** [comment]
I've solved this, by using `git mv` to ensure check the repo should have correct filenames, that's why I send this PR.

**Comment by jasl** [comment]
but I think github not showed this change, so in `Files changed` tab, you still get wrong filenames.

**Comment by varunest** [comment]
I think you got it wrong. Here take a look at this : 

https://github.com/jasl/AndroidPhotoFilters/blob/master/photofilterssdk/src/main/java/com/zomato/photofilters/imageprocessors/subfilters/SaturationSubfilter.java

This is from your master and it has file name 'SaturationSubfilter' whereas the class name is 'SaturationSubFilter'

**Comment by jasl** [comment]
I know this, but the base class is still named `SubFilter`, so I consider subclasses should conform this convention (otherwise, base class should rename to `Subfilter`).

In addition, the subclasses renamed as `Subfilter`, but in git, filenames still `SubFilter`, that's why people clone this repo, got files don't match with their respective class names issue.

**Comment by jasl** [comment]
If you think they should named `Subfilter`, I shall modify my PR to respect it.

**Comment by shubhamchaudhary** [comment]
Any update jasl?

**Comment by shubhamchaudhary** [comment]
Any update @jasl?

**Comment by jasl** [comment]
@shubhamchaudhary Sorry I forgot this, now I'm in vocation, go to work next week and will give a commit.

Sorry!

**Comment by jasl** [comment]
@shubhamchaudhary Sorry for delay, I've updated.

**Comment by ylogx** [comment]
Changes related to subclass name merged in #35. This PR had more than one change (changes in version numbers etc.)

**Pull request closed without merging**
